// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Named APP_DATABASE_URL (not DATABASE_URL) because DATABASE_URL is
    // already used by src/lib/tools/dbQuery.ts for the agent's optional
    // run_readonly_query tool, which points at a user's own external
    // database for QA validation — a completely different connection than
    // this app's own storage. Reusing the same name would let one silently
    // override the other if both are configured.
    url: process.env["APP_DATABASE_URL"],
  },
});
